[metadata]
name = ai-sathi-shared
version = 0.1.0
author = Akash Kundu
author_email = akashkundu1152@gmail.com
description = Shared utilities for AI‑SATHI project
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/AkashKundu114/AI-SATHI
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    =backend
packages = find:
python_requires = >=3.8
install_requires =
    sqlalchemy
    pydantic
    fastapi
    uvicorn
    python-dotenv
