from __future__ import annotations 

MAX_CHAT_RESPONSES_PER_DAY =40 
MAX_VOICE_TRANSCRIPTIONS_PER_DAY =15 
MAX_IMAGE_ANALYSES_PER_DAY =5 
MAX_POSTER_GENERATIONS_PER_DAY =2 
MAX_SCHEME_SEARCHES_PER_DAY =10 

MAX_CATALOG_CREATIONS_PER_DAY =MAX_IMAGE_ANALYSES_PER_DAY 
MAX_LEDGER_REPORTS_PER_DAY =10 
MAX_PRICE_CHAT_SESSIONS_PER_DAY =MAX_CHAT_RESPONSES_PER_DAY 

MIN_SECONDS_BETWEEN_REQUESTS =3 

CREDIT_COST_SARVAM_TEXT_STANDARD =1.0 
CREDIT_COST_SARVAM_TEXT_ADVANCED =2.0 
CREDIT_COST_SARVAM_VISION =3.0 
CREDIT_COST_SARVAM_STT =1.0 
CREDIT_COST_FLUX_POSTER =5.0 

BUDGET_DEGRADE_THRESHOLD =0.80 
BUDGET_HARD_STOP_THRESHOLD =0.95 
